# -*- coding: utf-8 -*-
"""test_route_between_cities.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwtMvTzIsiuWbSP43S77iBf_vWNTecoF

## Project 2 <a class="anchor" id="second"></a>
"""

import numpy as np
import pandas as pd

from global_temperature.route_between_cities import route_between_cities

df_MajorCity = pd.read_csv('global_temperature/data/GlobalLandTemperaturesByMajorCity.csv')
df_MajorCity.head()



object_1 = route_between_cities(df_MajorCity, year=2013, current_city='Peking', last_city='Los Angeles')

route = object_1.find_route()
route

object_1 = route_between_cities(df_MajorCity, year=1970, current_city='Peking', last_city='Los Angeles')

route = object_1.find_route()
route

object_1 = route_between_cities(df_MajorCity, year=2013, current_city='Chengdu', last_city='Los Angeles')

route = object_1.find_route()
route

object_1 = route_between_cities(df_MajorCity, year=2013, current_city='Guangzhou', last_city='Los Angeles')

route = object_1.find_route()
route

object_1 = route_between_cities(df_MajorCity, year=2013, current_city='Wuhan', last_city='Los Angeles')

route = object_1.find_route()
route

object_1 = route_between_cities(df_MajorCity, year=2013, current_city='Shenyang', last_city='Los Angeles')

route = object_1.find_route()
route

object_1 = route_between_cities(df_MajorCity, year=1970, current_city='Xian', last_city='Los Angeles')

route = object_1.find_route()
route

